version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}  
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   

  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "go.web@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "123456"
  #   ports:
  #     - "54321:80"
  #   depends_on:
  #     - postgres      